definitions:
  model.Auth:
    properties:
      avatar:
        type: string
      createTime:
        type: string
      creatorId:
        type: string
      deleted:
        type: boolean
      id:
        type: integer
      lastLoginIp:
        type: string
      merchantCode:
        type: string
      name:
        type: string
      password:
        type: string
      roleId:
        type: string
      status:
        type: boolean
      telephone:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.AuthSwag:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  model.Demo:
    properties:
      company:
        type: string
      count:
        type: string
      country:
        type: string
      extend:
        type: string
      id:
        type: integer
      items:
        type: string
      production:
        type: string
      serial:
        type: string
      uuid:
        type: string
      zoom:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/admin/auth/add:
    post:
      description: content 新增用户，不包括全权限
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Auth'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Auth'
      summary: 新增用户
      tags:
      - Admin
  /api/v1/admin/auth/all:
    get:
      description: 获取所有auth
      parameters:
      - description: token
        in: query
        name: token
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 获取所有auth
      tags:
      - Admin
  /api/v1/admin/auth/del/{id}:
    delete:
      description: 删除Auth
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 更新的目标auth id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除Auth
      tags:
      - Admin
  /api/v1/admin/auth/update/{id}:
    put:
      description: content 修改用户名或密码
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 更新的目标auth id
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Auth'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Auth'
      summary: 更新Auth
      tags:
      - Admin
  /api/v1/admin/auth/verify/{user}/{pwd}:
    get:
      description: 获取所有auth
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 用户名
        in: path
        name: user
        required: true
        type: string
      - description: 密码
        in: path
        name: pwd
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 获取所有auth
      tags:
      - Admin
  /api/v1/demo/add:
    post:
      description: 新增记录，只针对持久化数据
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Demo'
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 新增Demo记录
      tags:
      - Demo
  /api/v1/demo/del/{id}:
    delete:
      description: 删除记录
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 要删除的id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 删除Demo记录
      tags:
      - Demo
  /api/v1/demo/get:
    get:
      description: 获取value，逐级数据查询
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 查询key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Demo'
      summary: 查询指定key的值
      tags:
      - Demo
  /api/v1/demo/put/{id}:
    put:
      description: 修改指定id的内容
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 更新的id
        in: path
        name: id
        required: true
        type: string
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Demo'
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 修改Demo记录
      tags:
      - Demo
  /auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.AuthSwag'
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 200, "data": {}, "msg": "ok" }'
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 获取登录token 信息
      tags:
      - auth
swagger: "2.0"
