definitions:
  model.Auth:
    properties:
      avatar:
        type: string
      createTime:
        type: string
      creatorId:
        type: string
      deleted:
        type: boolean
      id:
        type: integer
      lastLoginIp:
        type: string
      merchantCode:
        type: string
      name:
        type: string
      password:
        type: string
      roleId:
        type: string
      status:
        type: boolean
      telephone:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.Claims:
    properties:
      auth:
        description: '对应Auth => Username  eg: admin'
        type: string
      id:
        type: integer
      type:
        description: '权限类型 eg: nav'
        type: string
      value:
        description: '权限指 eg: dashboard'
        type: string
    type: object
  model.Demo:
    properties:
      company:
        type: string
      count:
        type: string
      country:
        type: string
      extend:
        type: string
      id:
        type: integer
      items:
        type: string
      production:
        type: string
      serial:
        type: string
      uuid:
        type: string
      zoom:
        type: string
    type: object
  model.Nav:
    properties:
      component:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      parentId:
        type: integer
      path:
        type: string
      redirect:
        type: string
      show:
        type: boolean
      title:
        type: string
    type: object
host: 127.0.0.1:8888
info:
  contact:
    name: API Support
    url: http://www.swagger.io/support
  description: Gin API 接口模板服务
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin Template
  version: "1.0"
paths:
  /api/v1/admin/auth/add:
    post:
      description: content 新增用户，不包括全权限
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Auth'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Auth'
      security:
      - ApiKeyAuth: []
      summary: 新增用户
      tags:
      - Admin
  /api/v1/admin/auth/all:
    get:
      description: 获取所有auth
      parameters:
      - description: token
        in: query
        name: token
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取所有auth
      tags:
      - Admin
  /api/v1/admin/auth/del/{id}:
    delete:
      description: 删除Auth
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 更新的目标auth id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除Auth
      tags:
      - Admin
  /api/v1/admin/auth/update/{id}:
    put:
      description: content 修改用户名或密码
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 更新的目标auth id
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Auth'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Auth'
      security:
      - ApiKeyAuth: []
      summary: 更新Auth
      tags:
      - Admin
  /api/v1/admin/auth/verify/{user}/{pwd}:
    get:
      description: 获取所有auth
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 用户名
        in: path
        name: user
        required: true
        type: string
      - description: 密码
        in: path
        name: pwd
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取所有auth
      tags:
      - Admin
  /api/v1/admin/claims/add:
    post:
      description: content 新增用户，不包括全权限
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Claims'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Claims'
      security:
      - ApiKeyAuth: []
      summary: 新增用户
      tags:
      - Claims
  /api/v1/admin/claims/all:
    get:
      description: 获取当前用户所有claims
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户所有claims
      tags:
      - Claims
  /api/v1/admin/claims/del/{id}:
    delete:
      description: 删除Claims
      parameters:
      - description: 更新的目标claims id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除Claims
      tags:
      - Claims
  /api/v1/admin/claims/get:
    get:
      description: 获取当前用户所有claims
      parameters:
      - description: 指定用户
        in: query
        name: auth
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取当前用户所有claims
      tags:
      - Claims
  /api/v1/admin/claims/update/{id}:
    put:
      description: content 修改用户名或密码
      parameters:
      - description: 更新的目标claims id
        in: path
        name: id
        required: true
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Claims'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Claims'
      security:
      - ApiKeyAuth: []
      summary: 更新Claims
      tags:
      - Claims
  /api/v1/demo/add:
    post:
      description: 新增记录，只针对持久化数据
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Demo'
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增Demo记录
      tags:
      - Demo
  /api/v1/demo/del/{id}:
    delete:
      description: 删除记录
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 要删除的id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除Demo记录
      tags:
      - Demo
  /api/v1/demo/get:
    get:
      description: 获取value，逐级数据查询
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 查询key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Demo'
      security:
      - ApiKeyAuth: []
      summary: 查询指定key的值
      tags:
      - Demo
  /api/v1/demo/put/{id}:
    put:
      description: 修改指定id的内容
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: 更新的id
        in: path
        name: id
        required: true
        type: string
      - description: 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Demo'
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 修改Demo记录
      tags:
      - Demo
  /api/v1/nav/add:
    post:
      description: Nav POST ADD INTERFACE
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Nav'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Nav'
      security:
      - ApiKeyAuth: []
      summary: 新增接口
      tags:
      - Page
  /api/v1/nav/delete/{id}:
    delete:
      description: DELETE INTERFACE
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除接口
      tags:
      - Page
  /api/v1/nav/get:
    get:
      description: GET获取所有模板
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Nav'
      security:
      - ApiKeyAuth: []
      summary: Nav接口概要说明
      tags:
      - Page
  /api/v1/nav/put/{id}:
    put:
      description: UPDATE INTERFACE
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Nav'
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 修改接口
      tags:
      - Page
  /auth/login:
    post:
      description: 登陆、swagger、注销、404等
      parameters:
      - description: token
        in: query
        name: token
        type: string
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Auth'
      responses:
        "200":
          description: success
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 通用接口
      tags:
      - Auth
  /health:
    get:
      description: 接口健康检查接口
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
